future: true
permalink: /:title/
url: http://Chengwch.github.io
name: Vinson
author: Vinson
qq: 1193533843
email: chengwch3@163.com

duoshuo: Vinson
beian: 
cnzz: 
weibo: 
github: Chengwch
about: "这里是 Vinson 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
